CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR,
    email VARCHAR UNIQUE,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT unq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR,
    description VARCHAR,
    available BOOLEAN,
    owner_id BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_user FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS booking_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR,
    CONSTRAINT pk_booking_status PRIMARY KEY (id),
    CONSTRAINT unq_status UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    booking_start TIMESTAMP,
    booking_end TIMESTAMP,
    item_id BIGINT,
    booker_id BIGINT,
    status_id BIGINT,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users (id),
    CONSTRAINT fk_status FOREIGN KEY (status_id) REFERENCES booking_statuses (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);